# -*- coding: utf-8 -*-
"""Hierarchical Clustering

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CEfo-cNeKfePhgDpniaAyHqVsTpcbgkO
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('Mall_Customers.csv')

x = df.iloc[:,[3,4]].values

import scipy.cluster.hierarchy as sch
digram = sch.dendrogram(sch.linkage(x,method = 'ward'))
plt.title('Dendrogram')
plt.xlabel('Customers')
plt.ylabel('Euclidean Distance')

from sklearn.cluster import AgglomerativeClustering
hc = AgglomerativeClustering(n_clusters = 5, affinity = 'euclidean',linkage = 'ward')
y_pred = hc.fit_predict(x)

y_pred

from matplotlib.colors import ListedColormap
unique_cluster = np.unique(y_pred)
for i in range(len(unique_cluster)):
  labels = unique_cluster[i]
  indices = np.where(y_pred == labels)
  x_values = x[indices,0]
  y_values = x[indices,1]
  plt.scatter(x_values,y_values,label = labels,s = 100)